include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    public_member_api_docs: warning
    unused_import: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - ".dart_tool/**"

linter:
  rules:
    - always_declare_return_types
    - avoid_dynamic_calls
    - avoid_void_async
    - cascade_invocations
    - combinators_ordering
    - directives_ordering
    - eol_at_end_of_file
    - only_throw_errors
    - prefer_final_locals
    - prefer_single_quotes
    - public_member_api_docs
    - require_trailing_commas
    - sort_constructors_first
    - type_annotate_public_apis
    - unawaited_futures
    - use_super_parameters
