include: ../../analysis_options.yaml

analyzer:
  errors:
    public_member_api_docs: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - ".dart_tool/**"
